version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 975050101935.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t ws .
      - docker tag ws:latest 975050101935.dkr.ecr.us-east-1.amazonaws.com/ws:latest
  post_build:
    commands:
      - docker push 975050101935.dkr.ecr.us-east-1.amazonaws.com/ws:latest
      - echo Writing image definitions file...
      - printf '[{"name":"mywebsite","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json   
artifacts:
  files: imagedefinitions.json
